package com.example.hz.demospringboot.entity.hzim;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hz_users
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Users implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_users.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   应用ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_users.app_id
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_users.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_users.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_users.user_img
     *
     * @mbg.generated
     */
    private String userImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_users.nick
     *
     * @mbg.generated
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_users
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_users.user_id
     *
     * @return the value of hz_users.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_users.user_id
     *
     * @param userId the value for hz_users.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_users.app_id
     *
     * @return the value of hz_users.app_id
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_users.app_id
     *
     * @param appId the value for hz_users.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_users.create_time
     *
     * @return the value of hz_users.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_users.create_time
     *
     * @param createTime the value for hz_users.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_users.update_time
     *
     * @return the value of hz_users.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_users.update_time
     *
     * @param updateTime the value for hz_users.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_users.user_img
     *
     * @return the value of hz_users.user_img
     *
     * @mbg.generated
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_users.user_img
     *
     * @param userImg the value for hz_users.user_img
     *
     * @mbg.generated
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_users.nick
     *
     * @return the value of hz_users.nick
     *
     * @mbg.generated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_users.nick
     *
     * @param nick the value for hz_users.nick
     *
     * @mbg.generated
     */
    public void setNick(String nick) {
        this.nick = nick;
    }
}